---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ambassador-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ambassador
      sourceRef:
        kind: HelmRepository
        name: ambassador
      version: 6.7.13
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: ambassador
  targetNamespace: ambassador
  interval: 1m0s
  values:
    replicaCount: 2
    resources:
      limits:
        cpu: 1000m
        memory: 600Mi
      requests:
        cpu: 200m
        memory: 200Mi
    service:
      type: LoadBalancer
      annotations:
        # Enable proxy protocol
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
        # Specify whether the DigitalOcean Load Balancer should pass encrypted data to backend droplets
        service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
        # You can keep your existing LB when migrating to a new DOKS cluster, or when reinstalling AES
        kubernetes.digitalocean.com/load-balancer-id: "88583d5f-5d67-41d2-8719-48ef37d41bbd"
        service.kubernetes.io/do-loadbalancer-disown: false
