---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.0.13
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  interval: 1m0s
  values:
    controller:
      replicaCount: 2
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
      service:
        type: LoadBalancer
        annotations:
          # Enable proxy protocol
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
          # Specify whether the DigitalOcean Load Balancer should pass encrypted data to backend droplets
          service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
      config:
        use-proxy-protocol: "true"
