apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: do-api-credentials
  namespace: flux-system
spec:
  encryptedData:
    do_api_token: AgA7t+797VOpXeIIP896gkDRNy2ZL+7qizkVRUAsL2DYsmp6eNcNaOREooundAJqe4V3ssvmbs1Vh5zE+Rbv/K7qNNT9gmlEb6lLcop+m3QwidNWhFrG8rSKijfUiQniUdSAb55Yp35A2pf8/9UL+HFpNKBvtVcxc9qtq8gxBghYs+AMkzPnG/F5auyrUkUJ3kgoF4tqRMUahL8CaQKpgJiii0TPRbnrkpivzdTDWQB71VyzZhnuILWpsqt6oDizPs87Bnl5WPz7P0yOFp0RoRO2lPl0/3a4py4LHA4qneWIDXl3Aw82jH9UfrSQrsjbFXN5Fd4w5iDEsOUT5ZN8Aal6tkDKdPdb/upKOTz3pm+F6jJys8KNjrZY725z1k+KJ2wyjXuxXexHg5ARJUlp+HxB9mf77Ay3q/9Bm0/M5KbF9WXeavGbwpODv8X0d/8jqqN4RtIQypz2D8sB0DNmqFpG2RNwtLYxjYyah3lSHTLnQl3DI1x0IvLLB0BYsnO+Bqt6Hh7b+9uLclVvLToz9GaOS/BIyx+s5Xip501bal+cw4MJfRikncB6kl7V6qKat+eeDciOT7sTXlLUGSsv4ES3N1RT7Cd218NisrnP7jeE2D828GmyroaUqYI2wtUJlYSLqYrFlsUMC2D9ddGT6aQbA46HXr0Y1TeHOiQpPm4wUzGtoLyyPS/YCwsg0/MjbluVGhBZa9GgMkb9zIMdCzaBpI2MsRHp2efabnInurIsLyX1XXEcQOS9CsiORuuDb25ij/BLwOHvT02VyXBMCNvj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: do-api-credentials
      namespace: flux-system

