apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: do-spaces-credentials
  namespace: flux-system
spec:
  encryptedData:
    access_key_id: AgB3zdSVLHrfySfKGVpW8bHYAfTNQTAvYd+dV933+TkoaRfBG9iXTC8sh8TYn1D5yT8YzGiH4Ewl0Bmlm0uTz2kJAKcBPLKT9AJKR0w4Fa8l70UcdVuVB7uWGGFPHtRuGIDqohz9wR+MByawee0yHFuHfRvlsV06tM04hfkIj+avTFMYsZCpsjW3vfb9Xkv3k3DH/CTydQukpb0bLh/2qj9Xqx9GsBHiRfMVjG3smPGQnuyzGH6hZYUZ8Ev0nqj9lQADtYcx22sxBI9St8w+lhMkEQqGk5JG9Un77/ZgKc84K2DUXKo5M21DEIOVVhAtCF6I02geSd3YLDttK+z8PUKX/ayGJO8hdr1m2MfbZCE4xjNXzmYew5m3b6yxUN7i0LFXOhwSMzekE1YRyqvfBlV4iuGq3aoU+9rzOun3L9+F9vLd03vQ5xXBh6PBtNXYPL3ijJOp8aTpVRE7fpV4B1XZyu2zGm43gYwEpjh5Vj8J4Kcxldy2kgDHXzY27z+fEWsb+zKDWw1z9pJrwPcgUhVMDzbPKyWMlRrMqLfvnxaiq8GTjCwTzYDJJx282fnkCSObZtFrYFs53NroOJaQL004yol4/CS2KcgBtbIUErHZ8Wuthn40OOmt2M+w3VRiyRumDSPnE2cIPWkWhXWWPviIe6wofAM00wR5RLJCVAOaKw3EVB/SGWXTiM2x78cWYZdw5M42EEi3CvTrd8C3wRsq5/rXMQ==
    secret_access_key: AgAYAtnH/s1g2jtNet2rTnP1v/b9dVjAorBW7JCkLfTyXxLPmwSa8KzggOU0lOgpT9W8Dhn3Pk7gwBNUAwnuPIslSLTELNKo4mkV3CY3cKJ8cBWfEP3zq7lCM5aNC34MSG+KcBF794ePS9eC9rha18AUD9GWqDsKFX006UGKn10B6kSzoFxTytOGmajjkgZXaiRuJY0A0TJQIpcxex6aNt97d74Iy7eFYnV4qZeymNuZYIZz9pLPe9o+xVSH7z+F314Ac8rOXGOWb/dwnfLiV0oHOftAR/TgzyPn+ILL6nNsLFaOzK4KeyPv3Cj5311cVbulXLNxXwKiEJhL36NuSXDNidhLkpUJyHQAGcFoTJxvtuEHEAmUxF3HJoba3Ih/4U2bZrimWIHXRGxTJKwLfxw5AphkBs2NOdzaw+hZ3vLR/l+uc7IV0vRctlFMDzbTMDZ2XfxtLLxzH3nGNZc1/7OOvToi9Uo1WpUvUcjAtaTYRfChGkf3Z12CK9xkdJcaz/J3BaSauuz6QaZpMrKRWrX9ubXMcEZIRKlD0desGX90wMlooZHmxmo2iMVT+UIjAEsQey+KwzYe2ktdkEXHe2AvXxGnyxDuC7M26V2b8pUhc/EB7zdsUmOJR+E9J9AeXzCkp5P9W6JFH6ud3ur/bxWZ320A1HlUDCFWwRl51J1ZYAWVRRantzW2Ojd8eQYPpsCT+IRFizZVD6EodY170BtY20gB9KS7axEIJcHExmpkeNaStn+9Mo95MFxg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: do-spaces-credentials
      namespace: flux-system

