apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-stack-credentials
  namespace: flux-system
spec:
  encryptedData:
    grafana_admin_password: AgBuaTxRFpdn9zyYxrTo0GFS8Ltvh7xSUslF3EbRrKn7oZP83vKcddTizv8WN1rDDn9ayM1vJBd1DvX39Se+yNJUyTryc0Tl9MsLH7KRyqsAWHwxoRjPOeDZE4ZcIGLlDSX58CKvTtQLjOHRMbIdj4cG5FTIRP8Ze+ik6pish88aVNep/JK17Jkvt4FbZEi3VscpPgHQyBRitl6Mw3Oevs8mfWtNbRRlWT+axBJIcdcjUcXRJnoHsausa5OShfI5YfHP5fyqtFef1VidM5/aGczmwZo2EKj431j4EO25wqiwmOXANpP6SYi5u+YHcReWvd6huqnC8TdRpHwkGNyqlksYmpru/LtfCfb/x9weu2yuOX95iuVJjyhdb7ciKcL+Q8FYJsPvmpzzuiFR0XM+lR5UBgRVyr1ILLI1W7eP3wEVlKKhv0ewijy73d334bI/XKH3BEqdU8MhNB1RuSju5c0qBvHl73qCQksiLjt3Tng0AtR4YOmOIKdkCAHJOidOFhJc6ULmgJGMOTnKD6sXF7EngVW+OGMbMtMTRvNzy0Vdrq8CdJxseNxDAKzU3aKj4Fx1/QayrRO78lBcZHEW7hpczIWisPnMuFbBLcwKrjCTLgSc2xLOFSiI71ZndUlliNmBMOHB9TzBzE9ScndXs9w+qYUnS8svMxy1n85AtNPId2bIEFg0s+GoMRMrXkiyGpkL/SqBoLA4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prometheus-stack-credentials
      namespace: flux-system

