---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: echo
namespace: echo
resources:
  - echo_host_nginx.yaml
  - echo_deployment.yaml
  - echo_service.yaml
  - cert-manager-nginx-issuer.yaml
  - echo-ns.yaml