---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: quote
namespace: quote
resources:
  - quote_host_nginx.yaml
  - quote_deployment.yaml
  - quote_service.yaml
  - quote-ns.yaml